name: 'Test workflow'
on: [push]
jobs:
  lint:
    name: GraphQL Inspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: GraphQL Inspector
        uses: nutstick/graphql-inspector-action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_name: GraphQL Inspector
